name: Tests

on: [push, pull_request]

jobs:
    test:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: true
            matrix:
                php: [8.1]

        name: PHP ${{ matrix.php }}

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php }}
                  extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick, fileinfo
                  coverage: none

            - name: Setup problem matchers
              run: |
                  echo "::add-matcher::${{ runner.tool_cache }}/php.json"
                  echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"

            - name: Validate composer.json
              run: composer validate --strict

            - name: Lint files
              run: find src tests -name '*.php' | xargs -n 1 -P4 php -l

            - name: Install dependencies
              run: composer update --prefer-stable --prefer-dist --no-interaction

            - name: Execute tests
              run: vendor/bin/phpunit
              env:
                TEST_BOL_CLIENT_ID: ${{ secrets.TEST_BOL_CLIENT_ID }}
                TEST_BOL_CLIENT_SECRET: ${{ secrets.TEST_BOL_CLIENT_SECRET }}
